name: pro_health
description: A new Flutter application.

version: 1.0.0+2

environment:
  sdk: ">=2.2.0 <11.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  font_awesome_flutter: ^8.11.0
  flutter_svg: ^0.17.0
  flutter_screenutil: ^0.4.2
  smooth_star_rating: ^1.1.1
  intl: ^0.16.0
  flutter_launcher_icons: ^0.7.3
  flutter_launcher_name: ^0.0.1
  convex_bottom_bar: ^2.6.0
  scrolling_page_indicator: ^0.1.2
  icon_badge: ^0.0.1+5
  otp_screen: ^0.0.3
  smooth_page_indicator: ^0.2.0
  expansion_tile_card: ^1.1.0
  select_form_field: ^1.0.0
  flutter_datetime_picker: ^1.2.5
  custom_dropdown: ^0.0.2
  datetime_picker_formfield: ^1.0.0
  dropdown_search: ^0.4.8
  searchable_dropdown: ^1.1.0
  http: ^0.12.1
  rxdart: ^0.23.1
  dio: ^3.0.1
  find_dropdown: ^0.2.2
  grouped_buttons: ^1.0.4
  fdottedline: ^1.0.1
  html_editor: ^1.0.1
  simple_autocomplete_formfield: ^0.2.7
  flutter_sparkline: ^0.1.0
  flutter_staggered_grid_view: ^0.3.3
  responsive_widgets: ^0.1.10
  auto_animated: ^1.2.3
  flare_flutter: ^1.8.0
  flutter_staggered_animations: ^0.1.2
  page_transition: ^1.1.5
  cached_network_image: ^2.2.0+1
  flutter_spinkit: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/otp.png
    - assets/doctors.png
    - assets/drugs.png
    - assets/appointment.png
    - assets/adoctor.png
    - assets/apatient.png
    - assets/patient.png
    - assets/doctor.png
    - assets/doctor.png
    - assets/reports.png
    - assets/rx.png
    - assets/
  fonts:
    - family: Segoe
      fonts:
        - asset: assets/fonts/Segoeuil.ttf
          weight: 500
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito.ttf
    - family: RobotoMono
      fonts:
          - asset: assets/fonts/RobotoMono-Regular.ttf
          - asset: assets/fonts/RobotoMono-Bold.ttf
            weight: 700
          - asset: assets/fonts/RobotoMono-Medium.ttf
            weight: 600
    - family: RobotoMono-Medium
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
          weight: 600
    - family: RobotoMono-Bold
      fonts:
        - asset: assets/fonts/RobotoMono-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

flutter_launcher_name:
  name: "Pro Health"